// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dropthegroupid2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropthegroupid2));
        
        string IMigrationMetadata.Id
        {
            get { return "202202220624139_dropthegroupid2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
