//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Message_Id { get; set; }
        public string Message_Content { get; set; }
        public bool Message_Status { get; set; }
        public Nullable<System.DateTime> Sent_Date { get; set; }
        public Nullable<System.DateTime> Receiving_Date { get; set; }
        public int Request_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Message_Image1 { get; set; }
        public string Message_Image2 { get; set; }
        public string Message_Image3 { get; set; }
        public string Message_Image4 { get; set; }
        public string Message_Image5 { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
    }
}
