//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int Question_ID { get; set; }
        public string Question_Title { get; set; }
        public string Question_Details { get; set; }
        public string Answer_Content { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Reading_Count { get; set; }
        public Nullable<bool> TopLevel { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
