//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int Request_Id { get; set; }
        public string Request_Subject { get; set; }
        public Nullable<bool> Request_Status { get; set; }
        public Nullable<bool> Request_Undertaken { get; set; }
        public Nullable<System.DateTime> Request_Undertaken_Date { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Priority_ID { get; set; }
        public Nullable<int> Request_Undertaker_Id { get; set; }
        public Nullable<int> RequestCategory_ID { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual RequestCategory RequestCategory { get; set; }
        public virtual User User { get; set; }
    }
}
