//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Users
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string logintime { get; set; }
        public string Name_Surname { get; set; }
        public string DogumTarihi { get; set; }
        public string BaslamaTarihi { get; set; }
        public string Sube { get; set; }
        public string Bolum { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Faks { get; set; }
        public Nullable<short> Dahili { get; set; }
        public Nullable<int> Status { get; set; }
        public string TelefonNo { get; set; }
        public string FaksNo { get; set; }
        public string FirmaNo { get; set; }
        public Nullable<int> HesapTuru { get; set; }
        public string PreviousOffDates { get; set; }
        public Nullable<int> TotalYearly { get; set; }
        public string themename { get; set; }
        public string GsmNo { get; set; }
        public string Unvan { get; set; }
        public Nullable<int> PersonelTur { get; set; }
        public byte[] ModulSecimiArkaplan { get; set; }
        public byte[] Picture { get; set; }
        public string ContextID { get; set; }
        public Nullable<int> ChatStatus { get; set; }
        public string LastIPAddress { get; set; }
        public Nullable<int> FingerPrintNr { get; set; }
        public Nullable<int> FingerPrintBranch { get; set; }
        public string MuhasebeBaglantisi { get; set; }
        public Nullable<int> EFaturaUyesi { get; set; }
        public string EmailUsername { get; set; }
        public string EmailPassword { get; set; }
        public string DefaultCulture { get; set; }
        public string BorderColor { get; set; }
        public string BackgroundColor { get; set; }
        public string MuhasebeHesapPlani { get; set; }
        public Nullable<int> OnlyWebLogin { get; set; }
        public Nullable<int> ImpExp { get; set; }
    }
}
