//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int User_Permission_Id { get; set; }
        public bool Is_Authorized { get; set; }
        public bool Is_Active { get; set; }
        public int User_Group_Id { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
